version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: spooky
      POSTGRES_PASSWORD: spooky
      POSTGRES_DB: spooky
    restart: always
    networks:
      - sample
networks:
  sample:
